<a href="https://colab.research.google.com/github/Saransh-Bhatnagar/Music-Genre-Recognition/blob/main/Music_Genre_Recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


###**Music Genre Recognition using Artificial Neural Network in Deep learning**

####What is Music Genre Recognition?
Music Genre Recognition is an important field of research in Music Information Retrieval (MIR). A music genre is a conventional category that identifies some pieces of music as belonging to a shared tradition or set of conventions, i.e. it depicts the style of music.

The 10 genres are as follows:

0)Blues\
1)Classical\
2)Country\
3)Disco\
4)Hip-hop\
5)Jazz\
6)Metal\
7)Pop\
8)Reggae\
9)Rock



In [ ]:
#Importing the libraries
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import keras

#For optimizing and simplifying calculations and algos
import scipy

#For audio processing
import librosa

#Helps to display video,audio,text etc
import IPython.display as ipd

#For listing out all the audios we have
import glob

#For training the model
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#intalling pip
!pip install tensorflow_model_optimization

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


###features_3_sec
Our dataset consists of features of 10 genre each containing 100 songs of 30 seconds where each song is divided into 10 parts of 3 seconds.

In [ ]:
#Training the csv on the basis of features_30_sec.csv
df=pd.read_csv("/content/features_3_sec.csv")

In [ ]:
#Defining the shape of thr model
df.shape

(9990, 60)

In [ ]:
df.head #Displaying the data

<bound method NDFrame.head of                filename  length  chroma_stft_mean  chroma_stft_var  rms_mean  \
0     blues.00000.0.wav   66149          0.335406         0.091048  0.130405   
1     blues.00000.1.wav   66149          0.343065         0.086147  0.112699   
2     blues.00000.2.wav   66149          0.346815         0.092243  0.132003   
3     blues.00000.3.wav   66149          0.363639         0.086856  0.132565   
4     blues.00000.4.wav   66149          0.335579         0.088129  0.143289   
...                 ...     ...               ...              ...       ...   
9985   rock.00099.5.wav   66149          0.349126         0.080515  0.050019   
9986   rock.00099.6.wav   66149          0.372564         0.082626  0.057897   
9987   rock.00099.7.wav   66149          0.347481         0.089019  0.052403   
9988   rock.00099.8.wav   66149          0.387527         0.084815  0.066430   
9989   rock.00099.9.wav   66149          0.369293         0.086759  0.050524   

       rm

In [ ]:
df.dtypes #Displaying the datatypes

filename                    object
length                       int64
chroma_stft_mean           float64
chroma_stft_var            float64
rms_mean                   float64
rms_var                    float64
spectral_centroid_mean     float64
spectral_centroid_var      float64
spectral_bandwidth_mean    float64
spectral_bandwidth_var     float64
rolloff_mean               float64
rolloff_var                float64
zero_crossing_rate_mean    float64
zero_crossing_rate_var     float64
harmony_mean               float64
harmony_var                float64
perceptr_mean              float64
perceptr_var               float64
tempo                      float64
mfcc1_mean                 float64
mfcc1_var                  float64
mfcc2_mean                 float64
mfcc2_var                  float64
mfcc3_mean                 float64
mfcc3_var                  float64
mfcc4_mean                 float64
mfcc4_var                  float64
mfcc5_mean                 float64
mfcc5_var           

In [ ]:
df.drop(labels='filename',axis=1,inplace=True) #droping the column

In [ ]:
type_list=df.iloc[:,-1] # LabelEncoder().fit_transform fits the label encoder and return encoded labels.
y=LabelEncoder().fit_transform(type_list)
df.head()

length  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
0   66149          0.335406         0.091048  0.130405  0.003521   
1   66149          0.343065         0.086147  0.112699  0.001450   
2   66149          0.346815         0.092243  0.132003  0.004620   
3   66149          0.363639         0.086856  0.132565  0.002448   
4   66149          0.335579         0.088129  0.143289  0.001701   

   spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
0             1773.065032          167541.630869              1972.744388   
1             1816.693777           90525.690866              2010.051501   
2             1788.539719          111407.437613              2084.565132   
3             1655.289045          111952.284517              1960.039988   
4             1630.656199           79667.267654              1948.503884   

   spectral_bandwidth_var  rolloff_mean  ...  mfcc16_var  mfcc17_mean  \
0           117335.771563   3714.560359  ...   39.687145    -3.241280   
1            65671.875673   3869.682242  ...   64.748276    -6.055294   
2            75124.921716   3997.639160  ...   67.336563    -1.768610   
3            82913.639269   3568.300218  ...   47.739452    -3.841155   
4            60204.020268   3469.992864  ...   30.336359     0.664582   

   mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  mfcc20_mean  \
0   36.488243     0.722209   38.099152    -5.050335   33.618073    -0.243027   
1   40.677654     0.159015   51.264091    -2.837699   97.030830     5.784063   
2   28.348579     2.378768   45.717648    -1.938424   53.050835     2.517375   
3   28.337118     1.218588   34.770935    -3.580352   50.836224     3.630866   
4   45.880913     1.689446   51.363583    -3.392489   26.738789     0.536961   

   mfcc20_var  label  
0   43.771767  blues  
1   59.943081  blues  
2   33.105122  blues  
3   32.023678  blues  
4   29.146694  blues  

[5 rows x 59 columns]

In [ ]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
fit=StandardScaler()
print(df.iloc[:,:-1])
x=fit.fit_transform(np.array(df.iloc[:,:-1],dtype=float))
x

      length  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
0      66149          0.335406         0.091048  0.130405  0.003521   
1      66149          0.343065         0.086147  0.112699  0.001450   
2      66149          0.346815         0.092243  0.132003  0.004620   
3      66149          0.363639         0.086856  0.132565  0.002448   
4      66149          0.335579         0.088129  0.143289  0.001701   
...      ...               ...              ...       ...       ...   
9985   66149          0.349126         0.080515  0.050019  0.000097   
9986   66149          0.372564         0.082626  0.057897  0.000088   
9987   66149          0.347481         0.089019  0.052403  0.000701   
9988   66149          0.387527         0.084815  0.066430  0.000320   
9989   66149          0.369293         0.086759  0.050524  0.000067   

      spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
0                1773.065032          167541.630869              19

array([[ 0.        , -0.48780784,  0.64052047, ..., -0.51356204,
         0.12841417, -0.29178072],
       [ 0.        , -0.40314187,  0.13183473, ...,  1.01138445,
         1.27578001,  0.05642464],
       [ 0.        , -0.36169428,  0.7644909 , ..., -0.04624405,
         0.65390663, -0.52145798],
       ...,
       [ 0.        , -0.35433044,  0.42997426, ..., -0.15370124,
         0.11765485, -0.33882395],
       [ 0.        ,  0.0883611 , -0.00630133, ..., -0.72456977,
         0.30333409, -0.95893743],
       [ 0.        , -0.11321002,  0.19536324, ..., -0.37245283,
        -0.47495901, -0.55112155]])

In [ ]:
train_x,test_x,train_y,test_y = train_test_split(x,y,test_size=.30)
# Spliting the model into training and testing data usong test_size=0.30

In [ ]:
# Compiling and training
def tmodel(model,optimizer,epochs):
  model.compile(optimizer=optimizer,
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              metrics=['accuracy'])
  return model.fit(train_x,train_y,validation_data=(test_x,test_y),epochs=epochs,batch_size=256,callbacks= pruning_callback)

In [ ]:
# Defining the model
model=tf.keras.Sequential([
    tf.keras.layers.Dense(512,activation='relu',input_shape=(train_x.shape[1],)),
    tf.keras.layers.Dropout(.2),

    tf.keras.layers.Dense(256,activation='relu'),
    tf.keras.layers.Dropout(.2),

    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(.2),

    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dropout(.2),

    tf.keras.layers.Dense(10,activation='softmax')

])

In [ ]:
import tensorflow_model_optimization as tfmot
initial_sparsity = 0.0
final_sparsity = 0.75
begin_step = 50
end_step = 150
pruning_params = {
         'pruning_schedule': tfmot.sparsity.keras.PolynomialDecay(
             initial_sparsity=initial_sparsity,
            final_sparsity=final_sparsity,
            begin_step=begin_step,
            end_step=end_step)
     }
model = tfmot.sparsity.keras.prune_low_magnitude(model, **pruning_params)
pruning_callback = tfmot.sparsity.keras.UpdatePruningStep()

In [ ]:
# Training the model
fmodel=tmodel(model=model,optimizer='adam',epochs=800)

Epoch 1/800
28/28 [==============================] - 5s 24ms/step - loss: 1.7838 - accuracy: 0.3572 - val_loss: 1.2550 - val_accuracy: 0.5485
Epoch 2/800
28/28 [==============================] - 0s 16ms/step - loss: 1.2706 - accuracy: 0.5501 - val_loss: 0.9711 - val_accuracy: 0.6707
Epoch 3/800
28/28 [==============================] - 0s 17ms/step - loss: 1.0334 - accuracy: 0.6389 - val_loss: 0.8383 - val_accuracy: 0.7064
Epoch 4/800
28/28 [==============================] - 0s 17ms/step - loss: 0.9102 - accuracy: 0.6941 - val_loss: 0.7364 - val_accuracy: 0.7561
Epoch 5/800
28/28 [==============================] - 1s 22ms/step - loss: 0.8208 - accuracy: 0.7257 - val_loss: 0.6980 - val_accuracy: 0.7614
Epoch 6/800
28/28 [==============================] - 1s 27ms/step - loss: 0.7262 - accuracy: 0.7522 - val_loss: 0.6469 - val_accuracy: 0.7794
Epoch 7/800
28/28 [==============================] - 1s 34ms/step - loss: 0.6846 - accuracy: 0.7625 - val_loss: 0.5985 - val_accuracy: 0.7921
Epoch 

In [ ]:
# Displaying the test accuracy
test_loss, test_acc = model.evaluate(test_x, test_y, verbose=2)
print('\nTest accuracy:', test_acc*100)

94/94 - 0s - loss: 0.4128 - accuracy: 0.9366 - 202ms/epoch - 2ms/step

Test accuracy: 93.66032481193542


In [ ]:
dt=pd.read_csv("/content/Test (23)Bohemian Rhapsody.csv")
dt.drop(labels='filename',axis=1,inplace=True)
dt.head()
print(dt.iloc[:,:-1])
xt=fit.fit_transform(np.array(dt.iloc[:,:-1],dtype=float))
xt

   length  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
0  661794          0.402502           0.0888  0.119356  0.007014   

   spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
0             1211.066564          286920.933094              1454.654646   

   spectral_bandwidth_var  rolloff_mean  ...  mfcc16_mean  mfcc16_var  \
0           171309.113027   2374.477891  ...    -4.691229    78.86461   

   mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  \
0    -4.554178   65.608086    -1.806125   53.296383    -3.177989   57.550858   

   mfcc20_mean  mfcc20_var  
0    -3.685689    61.03611  

[1 rows x 58 columns]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#Predicting the model
predict = np.argmax(model.predict(dt.iloc[:,:-1]), axis=-1)

if predict==0:
     print('Blues')

elif predict==1:
    print('Classical')

elif predict==2:
    print('Country')

elif predict==3:
    print('Disco')

elif predict==4:
    print('HipHop')

elif predict==5:
    print('Jazz')

elif predict==6:
    print('Metal')

elif predict==7:
    print('Pop')

elif predict==8:
    print('Reggae')

elif predict==9:
    print('Rock')

1/1 [==============================] - 0s 16ms/step
Rock
